CREATE TABLE note (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    text VARCHAR(255) NOT NULL,
    created DATETIME NOT NULL
);